# Generated by Django 3.1.5 on 2021-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_type', models.CharField(choices=[('MJ', 'major'), ('GN', 'general'), ('MN', 'minor')], max_length=200)),
                ('grade', models.FloatField()),
                ('credits', models.FloatField()),
                ('standard', models.FloatField(choices=[('alt_1', 4.3), ('default', 4.5), ('alt_2', 3.7)])),
            ],
        ),
    ]
