# Generated by Django 3.1.5 on 2021-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_calculator', '0002_auto_20210127_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('MJ', 'major'), ('GN', 'general'), ('MN', 'minor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='desired_standard',
            field=models.FloatField(choices=[('default', 4.5), ('alt_1', 4.3), ('alt_2', 3.7)], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='standard',
            field=models.FloatField(choices=[('default', 4.5), ('alt_1', 4.3), ('alt_2', 3.7)], null=True),
        ),
    ]
