# Generated by Django 3.1.5 on 2021-01-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_calculator', '0003_auto_20210127_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('MJ', 'major'), ('MN', 'minor'), ('GN', 'general')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='desired_standard',
            field=models.FloatField(choices=[(4.5, '4.5'), (4.3, '4.3'), (3.7, '3.7')], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='standard',
            field=models.FloatField(choices=[(4.5, '4.5'), (4.3, '4.3'), (3.7, '3.7')], null=True),
        ),
    ]
