# Generated by Django 3.1.5 on 2021-02-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_calculator', '0005_auto_20210201_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('MJ', 'major'), ('GN', 'general'), ('MN', 'minor')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='standard',
            field=models.FloatField(choices=[(3.7, '3.7'), (4.3, '4.3'), (4.5, '4.5')], null=True),
        ),
    ]
