# Generated by Django 3.1.5 on 2021-02-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_calculator', '0006_auto_20210203_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='standard',
            field=models.FloatField(choices=[(4.5, '4.5'), (4.3, '4.3'), (3.7, '3.7')], null=True),
        ),
    ]
