# Generated by Django 3.1.5 on 2021-02-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_standard', models.FloatField(choices=[(3.7, '3.7'), (4.5, '4.5'), (4.3, '4.3')], null=True)),
                ('semester', models.CharField(choices=[('2020_1', '2020 SPRING'), ('2020_3', '2020 FALL'), ('2020_2', '2020 SUMMER'), ('2020_4', '2020 WINTER')], max_length=200, null=True)),
            ],
        ),
    ]
