# Generated by Django 3.1.5 on 2021-02-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='major_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='archive',
            name='minor_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='archive',
            name='total_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='archive',
            name='desired_standard',
            field=models.FloatField(choices=[(3.7, '3.7'), (4.3, '4.3'), (4.5, '4.5')], null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='semester',
            field=models.CharField(choices=[('2020_4', '2020 WINTER'), ('2020_2', '2020 SUMMER'), ('2020_1', '2020 SPRING'), ('2020_3', '2020 FALL')], max_length=200, null=True),
        ),
    ]
