# Generated by Django 3.1.5 on 2021-02-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20210203_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='desired_standard',
            field=models.FloatField(choices=[(4.5, '4.5'), (4.3, '4.3'), (3.7, '3.7')], null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='semester',
            field=models.CharField(choices=[('2020_2', '2020 SUMMER'), ('2020_4', '2020 WINTER'), ('2020_1', '2020 SPRING'), ('2020_3', '2020 FALL')], max_length=200, null=True),
        ),
    ]
