# Generated by Django 3.1.5 on 2021-02-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20210203_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='desired_standard',
        ),
        migrations.AddField(
            model_name='archive',
            name='desiredStandard',
            field=models.FloatField(choices=[(3.7, '3.7'), (4.3, '4.3'), (4.5, '4.5')], null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='semester',
            field=models.CharField(choices=[('2020_1', '2020 SPRING'), ('2020_3', '2020 FALL'), ('2020_2', '2020 SUMMER'), ('2020_4', '2020 WINTER')], max_length=200, null=True),
        ),
    ]
